/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author lugas
 */
public class Home extends javax.swing.JFrame {
    Pemeriksaan pemeriksaan = new Pemeriksaan();
    Registrasi registrasi = new Registrasi();
    Welcome welcome = new Welcome();
    Anamnesa anamnesa = new Anamnesa();
    Resep resep = new Resep();
    Pasien pasien = new Pasien();
    Dokter dokter = new Dokter();
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        body.add(welcome, "card2");
        body.setVisible(true);
        welcome.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        regBtn = new javax.swing.JButton();
        anamnesaBtn = new javax.swing.JButton();
        pmrBtn = new javax.swing.JButton();
        obatBtn = new javax.swing.JButton();
        psnBtn = new javax.swing.JButton();
        dokBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(51, 102, 255));
        header.setPreferredSize(new java.awt.Dimension(774, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1211, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        mainMenu.setBackground(new java.awt.Color(153, 153, 153));
        mainMenu.setPreferredSize(new java.awt.Dimension(200, 469));
        mainMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        regBtn.setText("Registrasi Pasien");
        regBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });
        mainMenu.add(regBtn);

        anamnesaBtn.setText("Anamnesa");
        anamnesaBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        anamnesaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anamnesaBtnMouseClicked(evt);
            }
        });
        anamnesaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamnesaBtnActionPerformed(evt);
            }
        });
        mainMenu.add(anamnesaBtn);

        pmrBtn.setText("Pemeriksaan");
        pmrBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        pmrBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmrBtnMouseClicked(evt);
            }
        });
        pmrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmrBtnActionPerformed(evt);
            }
        });
        mainMenu.add(pmrBtn);

        obatBtn.setText("Resep Obat");
        obatBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        obatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatBtnActionPerformed(evt);
            }
        });
        mainMenu.add(obatBtn);

        psnBtn.setText("Daftar Pasien");
        psnBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        psnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psnBtnActionPerformed(evt);
            }
        });
        mainMenu.add(psnBtn);

        dokBtn.setText("Daftar Dokter");
        dokBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        dokBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokBtnActionPerformed(evt);
            }
        });
        mainMenu.add(dokBtn);

        getContentPane().add(mainMenu, java.awt.BorderLayout.LINE_START);

        body.setLayout(new java.awt.CardLayout());
        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllPanel() {
        pemeriksaan.setVisible(false);      
        registrasi.setVisible(false);      
        welcome.setVisible(false);      
        anamnesa.setVisible(false);
        resep.setVisible(false);
        pasien.setVisible(false);
        dokter.setVisible(false);
    }
    
    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        this.clearAllPanel();
        pemeriksaan.setVisible(false);      

        body.add(registrasi, "card2");
        body.setVisible(true);
        registrasi.setVisible(true);
    }//GEN-LAST:event_regBtnActionPerformed

    private void pmrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmrBtnActionPerformed
        this.clearAllPanel();
                
        body.add(pemeriksaan, "card2");
        body.setVisible(true);
        pemeriksaan.setVisible(true);        
    }//GEN-LAST:event_pmrBtnActionPerformed

    private void pmrBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmrBtnMouseClicked
    }//GEN-LAST:event_pmrBtnMouseClicked

    private void anamnesaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anamnesaBtnMouseClicked
        this.clearAllPanel();
        
        body.add(anamnesa, "card2");
        body.setVisible(true);
        anamnesa.setVisible(true);
    }//GEN-LAST:event_anamnesaBtnMouseClicked

    private void anamnesaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamnesaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anamnesaBtnActionPerformed

    private void obatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatBtnActionPerformed
        // TODO add your handling code here:
        this.clearAllPanel();
        
        body.add(resep, "card2");
        body.setVisible(true);
        resep.setVisible(true);
    }//GEN-LAST:event_obatBtnActionPerformed

    private void psnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psnBtnActionPerformed
        // TODO add your handling code here:
        this.clearAllPanel();
        
        body.add(pasien, "card2");
        body.setVisible(true);
        pasien.setVisible(true);
    }//GEN-LAST:event_psnBtnActionPerformed

    private void dokBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokBtnActionPerformed
        // TODO add your handling code here:
        this.clearAllPanel();
        
        body.add(dokter, "card2");
        body.setVisible(true);
        dokter.setVisible(true);
    }//GEN-LAST:event_dokBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anamnesaBtn;
    private javax.swing.JPanel body;
    private javax.swing.JButton dokBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JButton obatBtn;
    private javax.swing.JButton pmrBtn;
    private javax.swing.JButton psnBtn;
    private javax.swing.JButton regBtn;
    // End of variables declaration//GEN-END:variables
}
